# Utiliser une image officielle Python comme base
FROM python:3.10-slim

# Définir le dossier de travail à l'intérieur du conteneur
WORKDIR /app

# Copier le fichier app.py dans le conteneur
COPY app.py .

# Lancer le script Python
CMD ["python", "app.py"]
